/* Auto-generated by scripts/sync-posts.js. Do not edit manually. */
window.COFFPEN_POSTS = Object.freeze([
  {
    "title": "سیاه و قلم",
    "url": "posts/%D8%AF%D8%B1%D9%88%D9%86-%D8%A8%D8%A7%D8%B7%D9%84-%D9%82%D8%B3%D9%85%D8%AA-%DB%B2.html",
    "filename": "درون-باطل-قسمت-۲.html",
    "description": "همچنان آن سایه‌ی سیاه به جان نگاه می‌کرد؛ نگاهی نه از روی دیدار، بلکه گویی به دنبال بیرون کشیدن چیزی از درون او بود انگار منتظر بود روح جان به شکل اعترافی بی‌صدا خودش را تسلیم کند. جان…",
    "author": "سهیل آقایانی",
    "series": "درون باطل",
    "episode": "2",
    "wordCount": 1048,
    "date": "2026-07-29T13:43:51.000Z",
    "empty": false
  },
  {
    "title": "درون باطل",
    "url": "posts/%D8%AF%D8%B1%D9%88%D9%86-%D8%A8%D8%A7%D8%B7%D9%84-%D9%82%D8%B3%D9%85%D8%AA-%DB%B1.html",
    "filename": "درون-باطل-قسمت-۱.html",
    "description": "جان با اضطراب راهی دیدار پدری می‌شود که هم نجات‌دهندهٔ او بوده و هم سرچشمهٔ رنجش؛ دیداری سرد در ایستگاه راه‌آهن که گذشته‌ای رازآلود را زنده می‌کند.",
    "author": "سهیل آقایانی",
    "series": "درون باطل",
    "episode": "1",
    "wordCount": 609,
    "date": "2026-07-29T13:39:47.000Z",
    "empty": false
  }
]);
